#!/bin/bash
#########################################
# AUTO GENERATED BY DEVTOOLS-MAVEN-PLUGIN
#########################################

if [ $# -le 0 ]; then
    echo "Invalid arguments! Please input the full class name (eg. com.mycompany.app.App) to execute." > /dev/tty
    exit 1;
fi

# THE CLASSPATH VARIABLE CONTAINING MAVEN DEPENDENCY JAR FILES
MVN_DEP_JARS=

# THE FINAL OUTPUT FILE AFTER BUILD TO RUN
EXEPKG=

java -cp ${EXEPKG}:${MVN_DEP_JARS} "$@"
